"""add tool_run table

Revision ID: 4956fba4caee
Revises: 952062f38a9d
Create Date: 2026-04-20 15:26:37.257742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4956fba4caee'
down_revision = '952062f38a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_tool_name'), ['tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_tool_runs_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_runs_status'))
        batch_op.drop_index(batch_op.f('ix_tool_runs_started_at'))

    op.drop_table('tool_runs')
    # ### end Alembic commands ###
