"""initial schema

Revision ID: 86aacfb3da11
Revises: 
Create Date: 2026-04-14 14:12:01.675107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86aacfb3da11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('host_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('enable_password_enc', sa.Text(), nullable=True),
    sa.Column('backup_command', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_expr', sa.String(length=50), nullable=True),
    sa.Column('retain_count', sa.Integer(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_auto_backup_enabled'), ['auto_backup_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_next_run'), ['next_run'], unique=False)

    op.create_table('host_template_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['host_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_expr', sa.String(length=50), nullable=True),
    sa.Column('retain_count', sa.Integer(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hosts_auto_backup_enabled'), ['auto_backup_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosts_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_hosts_next_run'), ['next_run'], unique=False)

    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_logs_logged_at'), ['logged_at'], unique=False)

    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('backup_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_runs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_runs_target_type'), ['target_type'], unique=False)

    op.create_table('host_file_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backup_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_alerts_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_alerts_run_id'), ['run_id'], unique=False)

    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backup_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_records_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_records_run_id'))

    op.drop_table('backup_records')
    with op.batch_alter_table('backup_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_alerts_run_id'))
        batch_op.drop_index(batch_op.f('ix_backup_alerts_is_read'))
        batch_op.drop_index(batch_op.f('ix_backup_alerts_created_at'))

    op.drop_table('backup_alerts')
    op.drop_table('host_file_paths')
    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_runs_target_type'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_status'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_host_id'))
        batch_op.drop_index(batch_op.f('ix_backup_runs_device_id'))

    op.drop_table('backup_runs')
    op.drop_table('user_groups')
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_logged_at'))

    op.drop_table('login_logs')
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hosts_next_run'))
        batch_op.drop_index(batch_op.f('ix_hosts_is_active'))
        batch_op.drop_index(batch_op.f('ix_hosts_group_id'))
        batch_op.drop_index(batch_op.f('ix_hosts_auto_backup_enabled'))

    op.drop_table('hosts')
    op.drop_table('host_template_paths')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_next_run'))
        batch_op.drop_index(batch_op.f('ix_devices_is_active'))
        batch_op.drop_index(batch_op.f('ix_devices_group_id'))
        batch_op.drop_index(batch_op.f('ix_devices_auto_backup_enabled'))

    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('host_templates')
    op.drop_table('groups')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
