"""empty message

Revision ID: 952062f38a9d
Revises: e0fa84dda3f1
Create Date: 2026-04-16 14:35:19.727781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952062f38a9d'
down_revision = 'e0fa84dda3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('last_message')

    # ### end Alembic commands ###
