"""add group_id to email_templates and scrapers

Revision ID: e0fa84dda3f1
Revises: b2d1e22fmode
Create Date: 2026-04-16 12:08:16.040380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fa84dda3f1'
down_revision = 'b2d1e22fmode'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_email_templates_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_email_templates_group_id', 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('scrapers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scrapers_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_scrapers_group_id', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scrapers_group_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scrapers_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_email_templates_group_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_email_templates_group_id'))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
